# This file was generated by nvfetcher, please do not modify it manually.
{fetchFromGitHub}: {
  dnscrypt-proxy-utils = {
    pname = "dnscrypt-proxy-utils";
    version = "2.1.5";
    src = fetchFromGitHub {
      owner = "DNSCrypt";
      repo = "dnscrypt-proxy";
      rev = "2.1.5";
      fetchSubmodules = false;
      sha256 = "sha256-A9Cu4wcJxrptd9CpgXw4eyMX2nmNAogYBRDeeAjpEZY=";
    };
  };
}
